services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root    # обязательно укажи свой пароль
      MYSQL_DATABASE: blog                  # опционально — создаст базу при старте                           # опционально — создает пользователя
      MYSQL_PASSWORD: root               # пароль для пользователя
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "3306:3306"   # проброс с хоста 3307 на 3306 контейнера
    volumes:
      - mysql-data:/var/lib/mysql   # для сохранения данных при перезапуске

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data: